-- Create table
/*==============================================================*/
/* Table: SYS_DEPT      公共字典                                */
/*==============================================================*/
CREATE TABLE "SYS_DICT" (
  ID VARCHAR2(64 BYTE) NOT NULL ,
  LABEL VARCHAR2(100 BYTE) NOT NULL ,
  VALUE VARCHAR2(100 BYTE) NOT NULL ,
  TYPE VARCHAR2(100 BYTE) NOT NULL ,
  DESCRIPTION VARCHAR2(100 BYTE) NOT NULL ,
  SORT NUMBER(10) NOT NULL ,
  CREATE_BY VARCHAR2(64 BYTE) NULL ,
  CREATE_DATE TIMESTAMP(7)  NULL ,
  UPDATE_BY VARCHAR2(64 BYTE) NULL ,
  UPDATE_DATE TIMESTAMP(7)  NULL ,
  REMARKS VARCHAR2(255 BYTE) NULL ,
  DEL_FLAG CHAR(1 BYTE) DEFAULT '0'  NOT NULL,
  INPUT_CODE VARCHAR2(10 BYTE) NULL
);
COMMENT ON TABLE "SYS_DICT" IS '字典表';
COMMENT ON COLUMN "SYS_DICT"."ID" IS '编号';
COMMENT ON COLUMN "SYS_DICT"."LABEL" IS '标签名';
COMMENT ON COLUMN "SYS_DICT"."VALUE" IS '数据值';
COMMENT ON COLUMN "SYS_DICT"."TYPE" IS '类型';
COMMENT ON COLUMN "SYS_DICT"."DESCRIPTION" IS '描述';
COMMENT ON COLUMN "SYS_DICT"."SORT" IS '排序（升序）';
COMMENT ON COLUMN "SYS_DICT"."CREATE_BY" IS '创建者';
COMMENT ON COLUMN "SYS_DICT"."CREATE_DATE" IS '创建时间';
COMMENT ON COLUMN "SYS_DICT"."UPDATE_BY" IS '更新者';
COMMENT ON COLUMN "SYS_DICT"."UPDATE_DATE" IS '更新时间';
COMMENT ON COLUMN "SYS_DICT"."REMARKS" IS '备注信息';
COMMENT ON COLUMN "SYS_DICT"."DEL_FLAG" IS '删除标记';

-- Create/Recreate primary, unique and foreign key constraints
alter table SYS_DICT
  add constraint PK_SYS_DICT primary key (id);
