/**
 * Created by heren on 2016/6/21.
 */

insert into SYS_DICT (ID, LABEL, VALUE, TYPE, DESCRIPTION, SORT, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE, REMARKS, DEL_FLAG, INPUT_CODE) values ('D52D14C80CCF4882A0C612F12C90A3A3', '机关', '1', 'UNIT_TYPE_DICT', '单位属性', 1, null, null, null, null, null, '0', 'JG');
insert into SYS_DICT (ID, LABEL, VALUE, TYPE, DESCRIPTION, SORT, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE, REMARKS, DEL_FLAG, INPUT_CODE) values ('315D06264B3B4C379663CDB6E48A753B', '部队', '2', 'UNIT_TYPE_DICT', '单位属性', 1, null, null, null, null, null, '0', 'BD');
insert into SYS_DICT (ID, LABEL, VALUE, TYPE, DESCRIPTION, SORT, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE, REMARKS, DEL_FLAG, INPUT_CODE) values ('B83F37A42C8A4DEE904AFC30E036717A', '院校、训练机构', '3', 'UNIT_TYPE_DICT', '单位属性', 1, null, null, null, null, null, '0', 'YXXLJG');
insert into SYS_DICT (ID, LABEL, VALUE, TYPE, DESCRIPTION, SORT, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE, REMARKS, DEL_FLAG, INPUT_CODE) values ('736FF4CB46464058BFB73D4691E6C7BE', '科研试验单位', '4', 'UNIT_TYPE_DICT', '单位属性', 1, null, null, null, null, null, '0', 'KYSYDW');
insert into SYS_DICT (ID, LABEL, VALUE, TYPE, DESCRIPTION, SORT, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE, REMARKS, DEL_FLAG, INPUT_CODE) values ('E4F0F606A5614E2CAE69DBD758DB7BC5', '机关直属单位', '5', 'UNIT_TYPE_DICT', '单位属性', 1, null, null, null, null, null, '0', 'JGZSDW');
insert into SYS_DICT (ID, LABEL, VALUE, TYPE, DESCRIPTION, SORT, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE, REMARKS, DEL_FLAG, INPUT_CODE) values ('4118F5EFBAB34AADADCAC43D2F916DB1', '预备役部队', '6', 'UNIT_TYPE_DICT', '单位属性', 1, null, null, null, null, null, '0', 'YBYBD');
insert into SYS_DICT (ID, LABEL, VALUE, TYPE, DESCRIPTION, SORT, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE, REMARKS, DEL_FLAG, INPUT_CODE) values ('A96EE57041FA4ED3AC23CD1045F4FB16', '其他单位', '9', 'UNIT_TYPE_DICT', '单位属性', 1, null, null, null, null, null, '0', 'QTDW');

