
--机构服务自定义对应系统服务
CREATE TABLE SERVICE_SELF_VS_SYS
(
   ID                 VARCHAR2(64)         NOT NULL,
   SELF_SERVICE_ID    VARCHAR2(64),
   SYS_SERVICE_ID     VARCHAR2(64),
   CONSTRAINT PK_SERVICE_SELF_VS_SYS PRIMARY KEY (ID)
);

COMMENT ON TABLE SERVICE_SELF_VS_SYS IS
'机构服务自定义对应系统服务';

COMMENT ON COLUMN SERVICE_SELF_VS_SYS.SELF_SERVICE_ID IS
'自定义服务ID';

COMMENT ON COLUMN SERVICE_SELF_VS_SYS.SYS_SERVICE_ID IS
'菜单所属原平台服务ID';